server {
    listen 80;
    server_name cleo-theo.eu.cc;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cleo-theo.eu.cc;

    ssl_certificate /etc/letsencrypt/live/cleo-theo.eu.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cleo-theo.eu.cc/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /root/dukou/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /v1/ {
        proxy_pass http://127.0.0.1:3456;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
    }
}
