server {
    listen 80;
    server_name cleo-theo.eu.cc;

    root /root/dukou/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /v1/ {
        proxy_pass http://127.0.0.1:3456;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
    }
}
